title: Environment Metadata
type: object
properties:
  telemetry_interval_sec:
    type: integer
  emergency_stop_sensitivity:
    type: number
    minimum: 0.0
    maximum: 1.0
required:
  - telemetry_interval_sec