control_loop_rate_hz: 50
watchdog_timeout_ms: 500

network:
  max_latency_ms: 100
  connection_timeout_ms: 2000
  reconnect_attempts: 3
  reconnect_interval_ms: 1000
  heartbeat_interval_ms: 250

logging:
  enable_packet_logging: true
  log_level: "info"  # debug, info, warn, error
  max_log_size_mb: 100
  retain_logs_days: 7

error_handling:
  max_consecutive_failures: 5
  failure_timeout_ms: 5000
  enable_auto_recovery: true