planning_frequency_hz: 20.0
control_frequency_hz: 50.0
planning_timeout_s: 1.0

path_following:
  lookahead_distance_m: 0.3
  lookahead_time_s: 0.5
  path_tolerance_m: 0.05
  goal_tolerance_m: 0.1
  heading_tolerance_rad: 0.05
  min_lookahead_distance_m: 0.1
  max_lookahead_distance_m: 0.5

trajectory:
  max_path_velocity_mps: 1.5
  min_path_velocity_mps: 0.1
  path_acceleration_mps2: 1.0
  path_deceleration_mps2: 1.2
  max_centripetal_acceleration_mps2: 0.5
  path_jerk_mps3: 0.5

local_planner:
  min_samples: 10
  max_samples: 50
  sampling_time_s: 0.8
  resolution_m: 0.05
  horizon_m: 2.0

global_planner:
  grid_resolution_m: 0.1
  inflation_radius_m: 0.5
  cost_scaling_factor: 2.0
  lethal_cost_value: 253
  neutral_cost_value: 50

obstacle_avoidance:
  min_obstacle_distance_m: 0.5
  max_obstacle_distance_m: 2.0
  obstacle_inflation_m: 0.2
  dynamic_obstacle_velocity_threshold_mps: 0.2

smoothing:
  curve_weight: 0.3
  smooth_weight: 0.3
  tolerance: 0.001
  max_iterations: 100

recovery:
  enable_backoff: true
  backoff_distance_m: 0.5
  enable_rotation_in_place: true
  max_rotation_angle_rad: 3.14
  clear_costmap_before_recovery: true