safety:
  emergency_stop_deceleration_mps2: 3.0
  min_obstacle_distance_m: 0.5
  timeout_ms: 100
  
  speed_limits:
    max_speed_normal_mps: 2.0
    max_speed_reduced_mps: 0.5
    max_speed_manual_mps: 1.0
  
  angular_motion_limits:
    max_angular_velocity_radps: 1.57  # ~90 degrees/second
    max_angular_acceleration_radps2: 2.0
  
  safety_zones:
    critical_zone_m: 0.3    # emergency stop if obstacle detected
    warning_zone_m: 1.0     # reduce speed if obstacle detected
    scanning_zone_m: 2.0    # start monitoring for obstacles
    
  system_checks:
    voltage_min_v: 22.0
    voltage_critical_v: 20.0
    temperature_max_c: 60.0
    watchdog_timeout_ms: 200
    
  recovery:
    max_retry_attempts: 3
    retry_delay_ms: 1000
    backoff_distance_m: 0.3